config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :m_companies
  resources :m_users
  resources :t_user_masters
  resources :m_roles
  resources :m_genders
end

app/models/m_user.rb
class MUser < ApplicationRecord
	belongs_to :m_company
end

app/controllers/m_users_controller.rb
class MUsersController < ApplicationController

  before_action :set_m_user , only: [:edit, :destroy, :update]
  
  def index
    @muser = MUser.all
  end

  def show
  end

  def new
    @muser = MUser.new
    @companies = MCompany.pluck(:company_name, :id)
  end

  def edit
    @companies = MCompany.pluck(:company_name, :id)
  end

  def create
    binding.pry
  	puts "============create============="
    @muser = MUser.new(m_users_params)
     respond_to do |format|
       if @muser.save
         format.html { redirect_to m_users_path , notice: 'Data was successfully saved.' }
       else
         @companies = MCompany.pluck(:company_name, :id)
         format.html { render :new }
       end
     end
  end

  def update
    respond_to do |format|
      if @muser.update(m_users_params)
        format.html { redirect_to m_users_path, notice: 'Data was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @muser.destroy
    respond_to do |format|
      format.html { redirect_to m_users_path , notice: 'Data was successfully deleted.' }
    end
  end
  
  private
  def m_users_params
    params.require(:m_user).permit(:user_id,
                                   :mail_id,
                                   :m_company_id,
									                 :password)  
  end

  def set_m_user
    @muser = MUser.find_by(id: params[:id])
  end

end

app/helpers/m_user_helper.rb
module MUserHelper
end

app/views/m_users/_form.html.erb
<h2>M User </h2>
<div class="container">
  <%= form_for @muser do |f| %>
    <div class="form-group">
      <%= f.label :user_id %><br>
      <%= f.text_field :user_id, autocomplete: "user_id", class: 'form-control' %>
    </div>
    <br>
    <div class="form-group">
        <%= f.label :mail_id %><br>
        <%= f.text_field :mail_id, autocomplete: "mail_id", class: 'form-control'  %>
    </div>
    <div>
      <%= f.label :m_company_id %>
      <%#= f.select :id, options_for_select(@companies.all.map{ |s| [s.company_name, s.id] })%>
      <%#= @companies %>
      <%= f.select :m_company_id , @companies %>
      <%#= f.collection_select :m_company_id, @companies, :id, :company_name %>
    </div>
    <br>
    <div class="form-group">
        <%= f.label :password %><br>
        <%= f.password_field :password, autocomplete: "password", class: 'form-control'  %>
    </div>
    <br>
    <div class="form-group">
        <%= f.submit "Submit", class: 'btn btn-primary btn-block' %>
    </div><br>
  <% end %>
</div>

app/views/m_users/edit.html.erb
<div class="col-sm-8 blog-main">

<h1>Editing M Roles</h1>

<%= render 'form', muser: @muser %>

<%= link_to 'Back', m_roles_path %> |

</div>

app/views/m_users/index.html.erb
<table>
  <thead>
    <th>Id</th>
    <th>User Id </th>
    <th>Mail Id</th>
    <th>Psssword</th>
    <th>M Company Id</th>
  </thead>
  <tbody>
    <% @muser.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= c.user_id %></td>
        <td><%= c.mail_id %></td>
        <td><%= c.password %></td>
        <td><%= c.m_company_id %></td>
        <td><%= link_to 'Edit', edit_m_user_path(id: c.id) %></td>
        <td><%= button_to 'Delete', m_user_path(id: c.id), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New", new_m_user_path %>

app/views/m_users/new.html.erb
<h2>M User </h2>
<div class="container2">
  <%= form_for @muser do |f| %>
    <div class="form-group">
      <%= f.label :user_id %><br>
      <%= f.text_field :user_id, autocomplete: "user_id", class: 'form-control' %>
    </div>
    <br>
    <div class="form-group">
        <%= f.label :mail_id %><br>
        <%= f.text_field :mail_id, autocomplete: "mail_id", class: 'form-control'  %>
    </div>
    <div>
      <%= f.label :m_company_id %>
      <%#= f.select :id, options_for_select(@companies.all.map{ |s| [s.company_name, s.id] })%>
      <%#= @companies %>
      <%= f.select :m_company_id , @companies %>
      <%#= f.collection_select :m_company_id, @companies, :id, :company_name %>
    </div>
    <br>
    <div class="form-group">
        <%= f.label :password %><br>
        <%= f.password_field :password, autocomplete: "password", class: 'form-control'  %>
    </div>
    <br>
    <div class="form-group">
        <%= f.submit "Submit", class: 'btn btn-primary btn-block' %>
    </div><br>
  <% end %>
</div>

app/views/m_users/sign_in.html.erb
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<div class="main">

        <!-- Sign up form -->
        <div class="signup">
            <div class="container">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Sign In</h2>
                        <form method="POST" class="register-form" id="register-form">
                            <div class="form-group">
                                <%= f.label :mail_id %><br>
                                <%= f.text_field :mail_id, autocomplete: "user_id", class: 'form-control' %>  
                            </div>
                            <div class="form-group">
                                <%= f.label :password %><br>
                                <%= f.password_field :password, autocomplete: "password", class: 'form-control'  %>
                            </div>
                            <div class="form-group">
                                <%= f.label :confirm_password %><br>
                                <%= f.password_field :confirm_password, autocomplete: "confirm_password", class: 'form-control'  %>
                            </div>
                            <div class="form-group form-button">
                                <%= f.submit "Submit", class: 'btn btn-primary btn-block' %>                        
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>