config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :m_companies
  resources :m_users
  resources :t_user_masters
  resources :m_roles
  resources :m_genders
end

app/models/t_user_master.rb
class TUserMaster < ApplicationRecord
    belongs_to :m_user
    belongs_to :m_gender
    belongs_to :m_role
end

app/controllers/t_user_masters_controller.rb
class TUserMastersController < ApplicationController

  before_action :set_t_user , only: [:edit, :destroy, :update]

  def index
    @tuser = TUserMaster.all
  end

  def new
    @tuser = TUserMaster.new
    @musers = MUser.pluck(:user_id, :id)    
    @mgenders = MGender.pluck(:gender_name, :id)
    @mroles = MRole.pluck(:role_name, :id)    
  end

  def show
  end

  def edit
    @musers = MUser.pluck(:user_id, :id) 
    @mgenders = MGender.pluck(:gender_name, :id)
    @mroles = MRole.pluck(:role_name, :id) 
  end

  def create
    puts "============create============="
    @tuser = TUserMaster.new(t_users_params)
     respond_to do |format|
       if @tuser.save
        format.html { redirect_to t_user_masters_path , notice: 'Data was successfully saved.' }
       else
        @musers = MUser.pluck(:user_id, :id)    
        @mgenders = MGender.pluck(:gender_name, :id)
        @mroles = MRole.pluck(:role_name, :id)
        format.html { render :new }
       end
     end
  end

  def update
    binding.pry
    respond_to do |format|
      if @tuser.update(t_users_params)
        format.html { redirect_to t_user_masters_path, notice: 'Data was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @tuser.destroy
    respond_to do |format|
      format.html { redirect_to t_user_masters_path , notice: 'Data was successfully deleted.' }
    end
  end

  private
  def t_users_params
    params.require(:t_user_master).permit(:m_user_id,
                                          :m_gender_id, 
                                          :m_role_id,
                                          :first_name,
                                          :last_name,
                                          :contact_no,
                                          :parents_contact_no,
                                          :address,
                                          :zairyo_card,
                                          :zairyo_card_expire_date,
                                          :adhar_card,
                                          :passport,
                                          :passport_expire_date,
                                          :my_number,
                                          :user_name
                                        )  
  end

  def set_t_user
    @tuser = TUserMaster.find_by(id: params[:id])
  end

end

app/views/t_user_masters/_form.html.erb
<h2>T User</h2>
<div class="container">
  <%= form_for @tuser do |f| %>
    <div>
      <%= f.label :m_user_id %>
      <%= f.select :m_user_id , @musers %>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name, autocomplete: "first_name", class: 'form-control' %>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name, autocomplete: "last_name", class: 'form-control'  %>
    </div>
    <div>
      <%= f.label :m_gender_id %>
      <%= f.select :m_gender_id, @mgenders %>

    </div>
    <div class="form-group">
      <%= f.label :contact_no %><br>
      <%= f.text_field :contact_no, autocomplete: "contact_no", class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= f.label :parents_contact_no %><br>
      <%= f.text_field :parents_contact_no, autocomplete: "parents_contact_no", class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= f.label :address %><br>
      <%= f.text_field :address, autocomplete: "address", class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= f.label :zairyo_card %><br>
      <%= f.text_field :zairyo_card, autocomplete: "zairyo_card", class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= f.label :zairyo_card_expire_date %><br>
      <%= f.text_field :zairyo_card_expire_date, autocomplete: "zairyo_card_expire_date", class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= f.label :adhar_card %><br>
      <%= f.text_field :adhar_card, autocomplete: "adhar_card", class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= f.label :passport %><br>
      <%= f.text_field :passport, autocomplete: "passport", class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= f.label :passport_expire_date %><br>
      <%= f.text_field :passport_expire_date, autocomplete: "passport_expire_date", class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= f.label :my_number %><br>
      <%= f.text_field :my_number, autocomplete: "my_number", class: 'form-control'  %>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :m_role_id %>
      <%= f.select :m_role_id, @mroles %>
    </div>
    <div class="form-group">
      <%= f.label :user_name %><br>
      <%= f.text_field :user_name, autocomplete: "user_name", class: 'form-control'  %>
    </div>
    <br>
    <div class="form-group">
      <%= f.submit "#{ tuser.id ? 'Update' : 'Create'}", class: 'btn btn-primary btn-block' %>
    </div><br>
  <% end %>
</div>

app/views/t_user_masters/edit.html.erb
<div class="col-sm-8 blog-main">

<h1>Editing T Tser</h1>

<%= render 'form', tuser: @tuser %>

<%= link_to 'Back', m_users_path %> |

</div>

app/views/t_user_masters/index.html.erb
<table>
  <thead>
    <th>Id</th>
    <th>M User </th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>M Gender</th>
    <th>Contact No</th>
    <th>Parents Contact</th>
    <th>Address</th>
    <th>Zairyo Card</th>
    <th>Zairyo Card Expire Date</th>
    <th>Adhar Card</th>
    <th>Passport</th>
    <th>Passport Expire Date</th>
    <th>My Number</th>
    <th>M Role</th>
    <th>User Name</th>
  </thead>
  <tbody>
    <% @tuser.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= c.m_user %></td>
        <td><%= c.first_name %></td>
        <td><%= c.last_name%></td>
        <td><%= c.m_gender %></td>
        <td><%= c.contact_no%></td>
        <td><%= c.parents_contact_no%></td>
        <td><%= c.address%></td>
        <td><%= c.zairyo_card%></td>
        <td><%= c.zairyo_card_expire_date%></td>
        <td><%= c.adhar_card%></td>
        <td><%= c.passport%></td>
        <td><%= c.passport_expire_date%></td>
        <td><%= c.my_number%></td>
        <td><%= c.m_role %></td>
        <td><%= c.user_name%></td>
        <td><%= link_to 'Edit', edit_t_user_master_path(id: c.id) %></td>
        <td><%= button_to "Delete", t_user_master_path(id: c.id), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New", new_t_user_master_path %>

app/views/t_user_masters/new.html.erb
<div class="col-sm-8 blog-main">

<h1>Create T Tser</h1>

<%= render 'form', tuser: @tuser %>

<%= link_to 'Back', m_users_path %> |

</div>