config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :m_companies
  resources :m_users
  resources :t_user_masters
  resources :m_roles
  resources :m_genders
end

app/models/m_role.rb
class MRole < ApplicationRecord
    has_many :t_user_master, dependent: :destroy
end

app/controllers/m_roles_controller.rb
class MRolesController < ApplicationController

  before_action :set_m_role , only: [:edit, :destroy, :update]

  def index
    @mrole = MRole.all
  end

  def new
    @mrole = MRole.new
  end

  def show
  end

  def create
    @mrole = MRole.new(m_role_params)
    respond_to do |format|
      if @mrole.save
        format.html { redirect_to m_roles_path , notice: 'Data was successfully saved.' }
      else
        format.html { render :new }
      end  
    end
  end

  def edit
  end
  
  def update
    respond_to do |format|
      if @mrole.update(m_role_params)
        format.html { redirect_to m_roles_path, notice: 'Data was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @mrole.destroy
    respond_to do |format|
      format.html { redirect_to m_roles_path , notice: 'Data was successfully deleted.' }
    end
  end

  private
  def m_role_params
    params.require(:m_role).permit(:role_name)  
  end

  def set_m_role
    @mrole = MRole.find_by(id: params[:id])
  end
  
end

app/helpers/m_roles_helper.rb
module MRolesHelper
end

app/views/m_roles/_form.html.erb
<h2>M Role </h2>
<div class="container">
  <%= form_for @mrole do |f| %>
    <div class="form-group">
      <%= f.label :role_name %><br>
      <%= f.text_field :role_name, autocomplete: "role_name", class: 'form-control' %>
    </div>
    <br>
    <div class="form-group">
        <%= f.submit "Submit", class: 'btn btn-primary btn-block' %>
    </div>
  <% end %>
</div>

app/views/m_roles/edit.html.erb
<div class="col-sm-8 blog-main">

<h1>Editing M Roles</h1>

<%= render 'form', mrole: @mrole %>

<%= link_to 'Back', m_roles_path %> |

</div>

app/views/m_roles/index.html.erb
<table>
  <thead>
    <th>Id</th>
    <th>Role Name </th>
  </thead>
  <tbody>
    <% @mrole.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= c.role_name %></td>
        <td><%= link_to 'Edit', edit_m_role_path(id: c.id) %></td>
        <td><%= button_to 'Delete', m_role_path(id: c.id), method: :delete%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New", new_m_role_path %>

app/views/m_roles/new.html.erb
<h2>M Role </h2>
<div class="container">
  <%= form_for @mrole do |f| %>
    <div class="form-group">
      <%= f.label :role_name %><br>
      <%= f.text_field :role_name, autocomplete: "role_name", class: 'form-control' %>
    </div>
    <br>
    <div class="form-group">
        <%= f.submit "Submit", class: 'btn btn-primary btn-block' %>
    </div>
  <% end %>
</div>