config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :m_companies
  resources :m_users
  resources :t_user_masters
  resources :m_roles
  resources :m_genders
end

app/models/m_company.rb
class MCompany < ApplicationRecord
  
  has_many :m_users
  #validates :company_name, presence: true, :with => /^[a-zA-Z]+$/i
  validates :address1, length: { maximum: 100 }
  validates :address2, length: { maximum: 100 }
  validates :email_id, format: { with: %r{[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\z}i }
end

app/controllers/m_companies_controller.rb
class MCompaniesController < ApplicationController
  include ApplicationHelper
  include EmailModule

  before_action :set_m_company , only: [:edit, :destroy, :update]

  def index
  	@mcompany = MCompany.all
  end

  def new
  	puts "==========new============"
  	@mcompany = MCompany.new 
  end

  def show
  end

  def create
    @mcompany = MCompany.new(m_company_params)
     respond_to do |format|
      if @mcompany.save
        format.html { redirect_to m_companies_path , notice: 'Data was successfully saved.' }
       else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @mcompany.update(m_company_params)
        format.html { redirect_to m_companies_path, notice: 'Data was successfully updated.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    binding.pry
    @mcompany = MCompany.find_by(id: params[:id])
    @mcompany.destroy
    respond_to do |format|
      format.html { redirect_to m_companies_path , notice: 'Data was successfully deleted.' }
    end
  end

  private
  def m_company_params
    params.require(:m_company).permit(:company_cd,
                                      :company_name,  
                                      :address1,
                                      :address2,
                                      :email_id, 
                                      :contact_no
                                    )
  end

  def set_m_company
    @mcompany = MCompany.find_by(id: params[:id])
  end
end

app/helpers/m_company_helper.rb
module MCompanyHelper
  
end

app/views/m_companies/_form.html.erb
<%= form_for @mcompany do |f| %>
  <div class="form-group">
    <%= f.label :company_cd %><br>
    <%= f.text_field :company_cd, autocomplete: "company_cd", class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name, autocomplete: "company_name", class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1, autocomplete: "address1", class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2, autocomplete: "address2", class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :email_id %><br>
    <%= f.text_field :email_id, autocomplete: "email_id", class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :contact_no %><br>
    <%= f.text_field :contact_no, autocomplete: "contact_no", class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.submit "#{ mcompany.id ? 'Update' : 'Create'}", class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/m_companies/edit.html.erb
<div class="col-sm-8 blog-main">

<h1>Editing M Company</h1>

<%= render 'form', mcompany: @mcompany %>

<%= link_to 'Back', m_companies_path %>

</div>

app/views/m_companies/index.html.erb
<table>
  <thead>
    <th>Id</th>
    <th>Company Code</th>
    <th>Company Name</th>
    <th>Address 1</th>
    <th>Address 2</th>
    <th>Email Id </th>
    <th>Contact no</th>
  </thead>
  <tbody>
    <% @mcompany.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= c.company_cd %></td>
        <td><%= c.company_name %></td>
        <td><%= c.address1 %></td>
        <td><%= c.address2 %></td>
        <td><%= c.email_id %></td>
        <td><%= c.contact_no %></td>
        <td><%= link_to 'Edit', edit_m_company_path(id: c.id) %></td>
        <td><%= button_to 'Delete', m_company_path(id: c.id) , method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New", new_m_company_path %>

app/views/m_companies/new.html.erb
<div class="col-sm-8 blog-main">

<h1>Create M Company</h1>

<%= render 'form', mcompany: @mcompany %>

<%= link_to 'Back', m_companies_path %> |

</div>